---
# Other bridge configurations...

# Bridge for ArUco marker velocity control
- ros_topic_name: "/model/target_aruco/cmd_vel"
  gz_topic_name: "/model/target_aruco/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ